########### Code to loop through multiple directories, each with multiple txt files, 
# and read each one into a row of a dataframe by subject and then combine them all.

#### Key Notes:
# pulled from Emily's mturk memories repository.
# Had to use toString to deal with misplaced (i.e. in the middle of text responses) new lines. 
# Also tried using read.delim, read.table with allowEscapes = TRUE, scan, read_lines, and readLines -- none worked.
# readChar looked promising, could be an alternate avenue to deal with the problem. 




###### Create a function that will take a path_name, memory_type and file_ending for each type of memory 
# (e.g. path_name = "\Data\Negative Memory 1"; memory_type = "Neg_Mem1"; file_ending = "_N1.txt") 
# and generate a dataframe with the full text and Subject number for each participant.  
  
# Note: Adapted from Kate Schertz's experimental design code and with much help from Claire Bergey.


create_txt_df <- function(path_name, memory_type, file_ending) {
  # make a list of all the text files in the folder identified by path_name
  file_list <- list.files(path = path_name, pattern = "\\.txt$")
  # create an empty dataframe to then stick elements into throughout the for loop
  dataset <- data.frame()
  # create a for loop that iterates over each text file, 
  # reads it in and labels the column with the memory type
  for (i in 1:length(file_list)) {
    # use toString to read in the text b/c read.delim, read.table and others will
    # break the text into separate rows at each new line (some participants included new lines
    # in their responses)
    text <- gsub(" , ", " ", toString(read_lines(file = paste0(path_name, "/", file_list[i]))))
    # remove the commas generated by using toString in two different patterns
    text <- gsub(".,",".",text)
    # create a temporary dataframe with the subject number and response text
    tempdat <- data.frame(str_replace(as.factor(file_list[i]), file_ending, ""),
                          text)
    colnames(tempdat) = c("Subject", memory_type)
    # This joins the current file to the earlier processed files
    dataset <- rbind(dataset, tempdat)
  }
  # output the dataframe
  return(dataset)
}


###### Create vectors that include all of the different arguments that will go into the function for all the different memory types:


path_names <- c("Data/Negative Memory 1", "Data/Negative Memory 2", "Data/Negative Memory 3",
                "Data/Adversity Memory 1", "Data/Adversity Memory 2", "Data/Adversity Memory 3")
memory_types <- c("Neg_Mem1", "Neg_Mem2", "Neg_Mem3", "Adv_Mem1", "Adv_Mem2", "Adv_Mem3")
file_endings <- c("_N1.txt", "_N2.txt", "_N3.txt", "_A1.txt", "_A2.txt", "_A3.txt")


##### Iterate the function over the parallel combination of the three vectors to create text_dfs (a list of dataframes).
# Then attach the original dataframe with the rest of the data into the list of dataframes (i.e. text_dfs) 
# so we can jon them all into a big dataframe (full_data).

text_dfs <- pmap(list(path_names, memory_types, file_endings), create_txt_df)
full_data <- append(text_dfs, list(df), 0) %>% reduce(left_join)
write.csv(full_data, "Data/full_data.csv", row.names = FALSE)
